#
# Module manifest for module 'RemoteScheduledTasks'
#
# Generated by: Sam Neal
#
# Generated on: 21/08/2020
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'RemoteScheduledTasks.psm1'

    # Version number of this module.
    ModuleVersion     = '0.1'

    # ID used to uniquely identify this module
    GUID              = '62eb54d3-e765-412d-8ea4-326c82c4ca60'

    # Author of this module
    Author            = 'Sam Neal'

    # Description of the functionality provided by this module
    Description       = 'A simple wrapper for PowerShells ScheduledTasks module to run against remote computers'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @("Start-RemoteScheduledTask", "Get-RemoteScheduledTask")

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @("ScheduledTasks", "TaskScheduler", "Tasks", "Scheduler")

            # A URL to the license for this module.
            LicenseUri = 'https://spdx.org/licenses/MIT.html'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/scv-m/RemoteScheduledTasks'
        }
    }
}
